name: plant_app_hey_flutter_challenge
description: Project implementing HeyFlutter coding challenge.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.3
  convenience_types: ^0.4.0
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  rxdart: ^0.27.7
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  hooks_riverpod: ^2.4.2
  flutter_hooks: ^0.20.2
  flutter_svg: ^2.0.7
  stack_trace: ^1.11.0
  collection: ^1.17.2
  json_annotation: ^4.8.1
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  freezed: ^2.3.4
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/intro/
    - assets/icons/
    - assets/images/

  fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: PlantAppIcons
      fonts:
        - asset: assets/icons/PlantAppIcons.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
