/// Flutter icons PlantApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PlantApp
///      fonts:
///       - asset: fonts/PlantApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class PlantAppIcons {
  PlantAppIcons._();

  static const _kFontFam = 'PlantAppIcons';
  static const String? _kFontPkg = null;

  static const IconData home_6_line =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData handbag_line =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
